/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_ajout_menu_ (void)
{
  GtkWidget *fenetre_ajout_menu_;
  GtkWidget *fixed1;
  GtkWidget *id_menu;
  GtkObject *spinbutton1_jour_adj;
  GtkWidget *spinbutton1_jour;
  GtkObject *spinbutton2_mois_adj;
  GtkWidget *spinbutton2_mois;
  GtkObject *spinbutton3_annee_adj;
  GtkWidget *spinbutton3_annee;
  GtkWidget *entree;
  GtkWidget *plat_principal;
  GtkWidget *dessert;
  GtkWidget *image1;
  GtkWidget *idmenu;
  GtkWidget *date;
  GtkWidget *jour;
  GtkWidget *mois;
  GtkWidget *annee;
  GtkWidget *type;
  GtkWidget *label9_REPAS;
  GtkWidget *entree1;
  GtkWidget *plat_principal1;
  GtkWidget *dessert1;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label14;
  GtkWidget *afficher;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *afficher1;
  GtkWidget *nature;
  GtkWidget *repas;
  GtkWidget *radiobutton1_HEALTHY;
  GSList *radiobutton1_HEALTHY_group = NULL;
  GtkWidget *radiobutton2_UNHEALTHY;
  GtkWidget *checkbutton1_SEL;
  GtkWidget *checkbutton2_GLUTEN;
  GtkWidget *combobox1_repas;

  fenetre_ajout_menu_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout_menu_), _("ajout menu"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout_menu_), fixed1);

  id_menu = gtk_entry_new ();
  gtk_widget_show (id_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), id_menu, 280, 16);
  gtk_widget_set_size_request (id_menu, 216, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_menu), 8226);

  spinbutton1_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_jour_adj), 1, 0);
  gtk_widget_show (spinbutton1_jour);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1_jour, 152, 88);
  gtk_widget_set_size_request (spinbutton1_jour, 56, 24);

  spinbutton2_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_mois_adj), 1, 0);
  gtk_widget_show (spinbutton2_mois);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2_mois, 312, 88);
  gtk_widget_set_size_request (spinbutton2_mois, 60, 27);

  spinbutton3_annee_adj = gtk_adjustment_new (2021, 2021, 2100, 1, 10, 10);
  spinbutton3_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_annee_adj), 1, 0);
  gtk_widget_show (spinbutton3_annee);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton3_annee, 488, 88);
  gtk_widget_set_size_request (spinbutton3_annee, 60, 27);

  entree = gtk_entry_new ();
  gtk_widget_show (entree);
  gtk_fixed_put (GTK_FIXED (fixed1), entree, 288, 328);
  gtk_widget_set_size_request (entree, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entree), 8226);

  plat_principal = gtk_entry_new ();
  gtk_widget_show (plat_principal);
  gtk_fixed_put (GTK_FIXED (fixed1), plat_principal, 288, 376);
  gtk_widget_set_size_request (plat_principal, 216, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (plat_principal), 8226);

  dessert = gtk_entry_new ();
  gtk_widget_show (dessert);
  gtk_fixed_put (GTK_FIXED (fixed1), dessert, 288, 432);
  gtk_widget_set_size_request (dessert, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (dessert), 8226);

  image1 = create_pixmap (fenetre_ajout_menu_, "index.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 192, 464);
  gtk_widget_set_size_request (image1, 296, 168);

  idmenu = gtk_label_new (Q_("<span color=\"darkblue\"> ENTRER L'IDENTIFIANT DU MENU : </span>"));
  gtk_widget_show (idmenu);
  gtk_fixed_put (GTK_FIXED (fixed1), idmenu, 0, 24);
  gtk_widget_set_size_request (idmenu, 248, 32);
  gtk_label_set_use_markup (GTK_LABEL (idmenu), TRUE);

  date = gtk_label_new (Q_("<span color=\"darkblue\"> DATE : </span>"));
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed1), date, 0, 80);
  gtk_widget_set_size_request (date, 72, 40);
  gtk_label_set_use_markup (GTK_LABEL (date), TRUE);

  jour = gtk_label_new (_("<span color =\"chocolate\"> JOUR </span>"));
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 80, 88);
  gtk_widget_set_size_request (jour, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (jour), TRUE);

  mois = gtk_label_new (_("<span color =\"chocolate\"> MOIS </span>"));
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 232, 88);
  gtk_widget_set_size_request (mois, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (mois), TRUE);

  annee = gtk_label_new (_("<span color =\"chocolate\"> ANNEE </span>"));
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 392, 88);
  gtk_widget_set_size_request (annee, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (annee), TRUE);

  type = gtk_label_new (_("<span color =\"darkblue\"> SELECTIONNER LE TYPE DE REPAS : </span>"));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed1), type, 8, 208);
  gtk_widget_set_size_request (type, 240, 33);
  gtk_label_set_use_markup (GTK_LABEL (type), TRUE);

  label9_REPAS = gtk_label_new (_("<span color =\"darkblue\"> REPAS :\n\302\260\302\260\302\260\302\260\302\260\302\260\302\260\302\260\302\260 </span>"));
  gtk_widget_show (label9_REPAS);
  gtk_fixed_put (GTK_FIXED (fixed1), label9_REPAS, 8, 328);
  gtk_widget_set_size_request (label9_REPAS, 72, 40);
  gtk_label_set_use_markup (GTK_LABEL (label9_REPAS), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label9_REPAS), 0.45, 0.5);

  entree1 = gtk_label_new (_("<span color =\"chocolate\"> ENTREE : </span>"));
  gtk_widget_show (entree1);
  gtk_fixed_put (GTK_FIXED (fixed1), entree1, 104, 328);
  gtk_widget_set_size_request (entree1, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (entree1), TRUE);

  plat_principal1 = gtk_label_new (_("<span color =\"chocolate\"> PLAT PRINCIPAL  : </span>"));
  gtk_widget_show (plat_principal1);
  gtk_fixed_put (GTK_FIXED (fixed1), plat_principal1, 104, 376);
  gtk_widget_set_size_request (plat_principal1, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (plat_principal1), TRUE);

  dessert1 = gtk_label_new (_("<span color =\"chocolate\"> DESSERT : </span>"));
  gtk_widget_show (dessert1);
  gtk_fixed_put (GTK_FIXED (fixed1), dessert1, 112, 432);
  gtk_widget_set_size_request (dessert1, 88, 33);
  gtk_label_set_use_markup (GTK_LABEL (dessert1), TRUE);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 40, 528);
  gtk_widget_set_size_request (ajouter, 144, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("<span color =\"brown\"> AJOUTER </span>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox1), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 496, 528);
  gtk_widget_set_size_request (afficher, 144, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (afficher), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  afficher1 = gtk_label_new_with_mnemonic (_("<span color =\"brown\"> AFFICHER  </span>"));
  gtk_widget_show (afficher1);
  gtk_box_pack_start (GTK_BOX (hbox2), afficher1, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (afficher1), TRUE);

  nature = gtk_label_new (_("<span color =\"darkblue\"> SELECTIONNER LA NATURE DE REPAS : </span>"));
  gtk_widget_show (nature);
  gtk_fixed_put (GTK_FIXED (fixed1), nature, 8, 272);
  gtk_widget_set_size_request (nature, 264, 40);
  gtk_label_set_use_markup (GTK_LABEL (nature), TRUE);

  repas = gtk_label_new (_("<span color =\"darkblue\"> SELECTIONNER LE REPAS : </span>"));
  gtk_widget_show (repas);
  gtk_fixed_put (GTK_FIXED (fixed1), repas, 8, 144);
  gtk_widget_set_size_request (repas, 184, 32);
  gtk_label_set_use_markup (GTK_LABEL (repas), TRUE);

  radiobutton1_HEALTHY = gtk_radio_button_new_with_mnemonic (NULL, _(" HEALTHY "));
  gtk_widget_show (radiobutton1_HEALTHY);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1_HEALTHY, 296, 208);
  gtk_widget_set_size_request (radiobutton1_HEALTHY, 120, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_HEALTHY), radiobutton1_HEALTHY_group);
  radiobutton1_HEALTHY_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_HEALTHY));

  radiobutton2_UNHEALTHY = gtk_radio_button_new_with_mnemonic (NULL, _("UNHEALTHY"));
  gtk_widget_show (radiobutton2_UNHEALTHY);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2_UNHEALTHY, 464, 208);
  gtk_widget_set_size_request (radiobutton2_UNHEALTHY, 128, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_UNHEALTHY), radiobutton1_HEALTHY_group);
  radiobutton1_HEALTHY_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_UNHEALTHY));

  checkbutton1_SEL = gtk_check_button_new_with_mnemonic (_("SANS SEL"));
  gtk_widget_show (checkbutton1_SEL);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1_SEL, 296, 272);
  gtk_widget_set_size_request (checkbutton1_SEL, 128, 40);

  checkbutton2_GLUTEN = gtk_check_button_new_with_mnemonic (_("SANS GLUTEN"));
  gtk_widget_show (checkbutton2_GLUTEN);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton2_GLUTEN, 464, 272);
  gtk_widget_set_size_request (checkbutton2_GLUTEN, 144, 40);

  combobox1_repas = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1_repas);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1_repas, 280, 144);
  gtk_widget_set_size_request (combobox1_repas, 217, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_repas), _("PETIT DEJEUNER "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_repas), _("DEJEUNER"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_repas), _("DINER"));

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_HEALTHY, "toggled",
                    G_CALLBACK (on_radiobutton1_HEALTHY_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_UNHEALTHY, "toggled",
                    G_CALLBACK (on_radiobutton2_UNHEALTHY_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_SEL, "toggled",
                    G_CALLBACK (on_checkbutton1_SEL_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2_GLUTEN, "toggled",
                    G_CALLBACK (on_checkbutton2_GLUTEN_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout_menu_, fenetre_ajout_menu_, "fenetre_ajout_menu_");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, id_menu, "id_menu");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, spinbutton1_jour, "spinbutton1_jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, spinbutton2_mois, "spinbutton2_mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, spinbutton3_annee, "spinbutton3_annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, entree, "entree");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, plat_principal, "plat_principal");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, dessert, "dessert");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, idmenu, "idmenu");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, date, "date");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, type, "type");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, label9_REPAS, "label9_REPAS");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, entree1, "entree1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, plat_principal1, "plat_principal1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, dessert1, "dessert1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, label14, "label14");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, afficher1, "afficher1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, nature, "nature");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, repas, "repas");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, radiobutton1_HEALTHY, "radiobutton1_HEALTHY");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, radiobutton2_UNHEALTHY, "radiobutton2_UNHEALTHY");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, checkbutton1_SEL, "checkbutton1_SEL");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, checkbutton2_GLUTEN, "checkbutton2_GLUTEN");
  GLADE_HOOKUP_OBJECT (fenetre_ajout_menu_, combobox1_repas, "combobox1_repas");

  return fenetre_ajout_menu_;
}

GtkWidget*
create_fenetre_affiche_menu (void)
{
  GtkWidget *fenetre_affiche_menu;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *entry5_iden;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *image8;
  GtkWidget *image7;
  GtkWidget *label17_iden;
  GtkWidget *chercher_;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label34;
  GtkWidget *button_modifier_dorra;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image16;
  GtkWidget *label40;
  GtkWidget *label38;
  GtkWidget *SUPP_DORRA;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image15;
  GtkWidget *label39;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *RETOOUR_1_AFFICHE;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image21;
  GtkWidget *label48;
  GtkWidget *liste;
  GtkWidget *button2_actualiiser_affiiche;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image22;
  GtkWidget *label49;

  fenetre_affiche_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_affiche_menu), _("affiche menu"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_affiche_menu), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 0, 80);
  gtk_widget_set_size_request (treeview1, 936, 384);

  entry5_iden = gtk_entry_new ();
  gtk_widget_show (entry5_iden);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5_iden, 1120, 24);
  gtk_widget_set_size_request (entry5_iden, 216, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_iden), 8226);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator1, 360, 0);
  gtk_widget_set_size_request (vseparator1, 72, 312);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator2, 440, 8);
  gtk_widget_set_size_request (vseparator2, 24, 352);

  image8 = create_pixmap (fenetre_affiche_menu, "index.png");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed2), image8, 832, 464);
  gtk_widget_set_size_request (image8, 272, 149);

  image7 = create_pixmap (fenetre_affiche_menu, "66.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed2), image7, 928, 96);
  gtk_widget_set_size_request (image7, 72, 272);

  label17_iden = gtk_label_new (_("<span color =\"darkblue\"> ENTRER L'IDENTIFIANT : </span>"));
  gtk_widget_show (label17_iden);
  gtk_fixed_put (GTK_FIXED (fixed2), label17_iden, 928, 16);
  gtk_widget_set_size_request (label17_iden, 192, 48);
  gtk_label_set_use_markup (GTK_LABEL (label17_iden), TRUE);

  chercher_ = gtk_button_new ();
  gtk_widget_show (chercher_);
  gtk_fixed_put (GTK_FIXED (fixed2), chercher_, 1096, 144);
  gtk_widget_set_size_request (chercher_, 170, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (chercher_), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("<span color =\"chocolate\"> CHERCHER </span>"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox7), label34, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  button_modifier_dorra = gtk_button_new ();
  gtk_widget_show (button_modifier_dorra);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifier_dorra, 1104, 352);
  gtk_widget_set_size_request (button_modifier_dorra, 168, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_modifier_dorra), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox11), image16, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("<span color =\"chocolate\">MODIFIER </span>"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox11), label40, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label38 = gtk_label_new (_("<span color =\"chocolate\"> \n \n</span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed2), label38, 1040, 88);
  gtk_widget_set_size_request (label38, 248, 40);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  SUPP_DORRA = gtk_button_new ();
  gtk_widget_show (SUPP_DORRA);
  gtk_fixed_put (GTK_FIXED (fixed2), SUPP_DORRA, 1096, 240);
  gtk_widget_set_size_request (SUPP_DORRA, 176, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0.16, 0.06);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (SUPP_DORRA), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox10), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("<span color =\"chocolate\">SUPPRIMER  </span>"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox10), label39, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  label41 = gtk_label_new ("");
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed2), label41, 1048, 296);
  gtk_widget_set_size_request (label41, 248, 40);

  label42 = gtk_label_new ("");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed2), label42, 1056, 424);
  gtk_widget_set_size_request (label42, 264, 32);

  RETOOUR_1_AFFICHE = gtk_button_new ();
  gtk_widget_show (RETOOUR_1_AFFICHE);
  gtk_fixed_put (GTK_FIXED (fixed2), RETOOUR_1_AFFICHE, 32, 536);
  gtk_widget_set_size_request (RETOOUR_1_AFFICHE, 152, 56);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (RETOOUR_1_AFFICHE), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image21 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox16), image21, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("<span color =\"chocolate\" >    RETOURNER </span>"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox16), label48, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  liste = gtk_label_new (_("<span color =\"darkblue\">  LISTE DES MENUS : \n*******************</span>"));
  gtk_widget_show (liste);
  gtk_fixed_put (GTK_FIXED (fixed2), liste, 336, 8);
  gtk_widget_set_size_request (liste, 216, 48);
  gtk_label_set_use_markup (GTK_LABEL (liste), TRUE);

  button2_actualiiser_affiiche = gtk_button_new ();
  gtk_widget_show (button2_actualiiser_affiiche);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_actualiiser_affiiche, 440, 528);
  gtk_widget_set_size_request (button2_actualiiser_affiiche, 152, 56);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button2_actualiiser_affiiche), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image22 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox17), image22, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("<span color =\"chocolate\"> ACTUALISER </span>"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox17), label49, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) chercher_, "clicked",
                    G_CALLBACK (on_chercher__clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_dorra, "clicked",
                    G_CALLBACK (on_button_modifier_dorra_clicked),
                    NULL);
  g_signal_connect ((gpointer) SUPP_DORRA, "clicked",
                    G_CALLBACK (on_SUPP_DORRA_clicked),
                    NULL);
  g_signal_connect ((gpointer) RETOOUR_1_AFFICHE, "clicked",
                    G_CALLBACK (on_RETOOUR_1_AFFICHE_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_actualiiser_affiiche, "clicked",
                    G_CALLBACK (on_button2_actualiiser_affiiche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_affiche_menu, fenetre_affiche_menu, "fenetre_affiche_menu");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, entry5_iden, "entry5_iden");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image8, "image8");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image7, "image7");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label17_iden, "label17_iden");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, chercher_, "chercher_");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image12, "image12");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label34, "label34");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, button_modifier_dorra, "button_modifier_dorra");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label40, "label40");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label38, "label38");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, SUPP_DORRA, "SUPP_DORRA");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image15, "image15");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label39, "label39");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label41, "label41");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label42, "label42");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, RETOOUR_1_AFFICHE, "RETOOUR_1_AFFICHE");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image21, "image21");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label48, "label48");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, liste, "liste");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, button2_actualiiser_affiiche, "button2_actualiiser_affiiche");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, image22, "image22");
  GLADE_HOOKUP_OBJECT (fenetre_affiche_menu, label49, "label49");

  return fenetre_affiche_menu;
}

GtkWidget*
create_fenetre_modifier (void)
{
  GtkWidget *fenetre_modifier;
  GtkWidget *fixed3;
  GtkWidget *entry6_idm;
  GtkWidget *ENTREE_2;
  GtkWidget *entry8_PP;
  GtkWidget *entry9_DESSERT;
  GtkWidget *label21_date;
  GtkWidget *label22_jour;
  GtkWidget *label23_mois;
  GtkWidget *label24_annee;
  GtkWidget *label25_type;
  GtkWidget *label26_REPAS;
  GtkWidget *label27_ENTREE;
  GtkWidget *label28_PP;
  GtkWidget *label29_DESSERT;
  GtkWidget *label20_idm;
  GtkWidget *label32_nature;
  GtkWidget *label33_repas;
  GtkWidget *MODIFIER;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label36;
  GtkWidget *image9;
  GtkWidget *label43;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *combobox1;
  GtkWidget *checkbutton_22_GLUTEN;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image18;
  GtkWidget *label45;
  GtkWidget *radiobutton5_HEALTHY;
  GSList *radiobutton5_HEALTHY_group = NULL;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image19;
  GtkWidget *label46;
  GtkWidget *radiobutton6_UNHEALTHY;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image20;
  GtkWidget *label47;
  GtkWidget *checkbutton_11_sel;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image17;
  GtkWidget *label44;
  GtkWidget *button_3_retour_modif;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image23;
  GtkWidget *label50;

  fenetre_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_modifier), _("modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_modifier), fixed3);

  entry6_idm = gtk_entry_new ();
  gtk_widget_show (entry6_idm);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6_idm, 280, 16);
  gtk_widget_set_size_request (entry6_idm, 216, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6_idm), 8226);

  ENTREE_2 = gtk_entry_new ();
  gtk_widget_show (ENTREE_2);
  gtk_fixed_put (GTK_FIXED (fixed3), ENTREE_2, 288, 328);
  gtk_widget_set_size_request (ENTREE_2, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ENTREE_2), 8226);

  entry8_PP = gtk_entry_new ();
  gtk_widget_show (entry8_PP);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8_PP, 288, 376);
  gtk_widget_set_size_request (entry8_PP, 216, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8_PP), 8226);

  entry9_DESSERT = gtk_entry_new ();
  gtk_widget_show (entry9_DESSERT);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9_DESSERT, 288, 432);
  gtk_widget_set_size_request (entry9_DESSERT, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9_DESSERT), 8226);

  label21_date = gtk_label_new (Q_("<span color=\"darkblue\"> DATE : </span>"));
  gtk_widget_show (label21_date);
  gtk_fixed_put (GTK_FIXED (fixed3), label21_date, 0, 80);
  gtk_widget_set_size_request (label21_date, 72, 40);
  gtk_label_set_use_markup (GTK_LABEL (label21_date), TRUE);

  label22_jour = gtk_label_new (_("<span color =\"chocolate\"> JOUR </span>"));
  gtk_widget_show (label22_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), label22_jour, 80, 88);
  gtk_widget_set_size_request (label22_jour, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label22_jour), TRUE);

  label23_mois = gtk_label_new (_("<span color =\"chocolate\"> MOIS </span>"));
  gtk_widget_show (label23_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), label23_mois, 232, 88);
  gtk_widget_set_size_request (label23_mois, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (label23_mois), TRUE);

  label24_annee = gtk_label_new (_("<span color =\"chocolate\"> ANNEE </span>"));
  gtk_widget_show (label24_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), label24_annee, 392, 88);
  gtk_widget_set_size_request (label24_annee, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label24_annee), TRUE);

  label25_type = gtk_label_new (_("<span color =\"darkblue\"> SELECTIONNER LE TYPE DE REPAS : </span>"));
  gtk_widget_show (label25_type);
  gtk_fixed_put (GTK_FIXED (fixed3), label25_type, 8, 208);
  gtk_widget_set_size_request (label25_type, 240, 33);
  gtk_label_set_use_markup (GTK_LABEL (label25_type), TRUE);

  label26_REPAS = gtk_label_new (_("<span color =\"darkblue\"> REPAS :\n\302\260\302\260\302\260\302\260\302\260\302\260\302\260\302\260\302\260 </span>"));
  gtk_widget_show (label26_REPAS);
  gtk_fixed_put (GTK_FIXED (fixed3), label26_REPAS, 8, 328);
  gtk_widget_set_size_request (label26_REPAS, 72, 40);
  gtk_label_set_use_markup (GTK_LABEL (label26_REPAS), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label26_REPAS), 0.45, 0.5);

  label27_ENTREE = gtk_label_new (_("<span color =\"chocolate\"> ENTREE : </span>"));
  gtk_widget_show (label27_ENTREE);
  gtk_fixed_put (GTK_FIXED (fixed3), label27_ENTREE, 104, 328);
  gtk_widget_set_size_request (label27_ENTREE, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label27_ENTREE), TRUE);

  label28_PP = gtk_label_new (_("<span color =\"chocolate\"> PLAT PRINCIPAL  : </span>"));
  gtk_widget_show (label28_PP);
  gtk_fixed_put (GTK_FIXED (fixed3), label28_PP, 104, 376);
  gtk_widget_set_size_request (label28_PP, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (label28_PP), TRUE);

  label29_DESSERT = gtk_label_new (_("<span color =\"chocolate\"> DESSERT : </span>"));
  gtk_widget_show (label29_DESSERT);
  gtk_fixed_put (GTK_FIXED (fixed3), label29_DESSERT, 112, 432);
  gtk_widget_set_size_request (label29_DESSERT, 88, 33);
  gtk_label_set_use_markup (GTK_LABEL (label29_DESSERT), TRUE);

  label20_idm = gtk_label_new (Q_("<span color=\"darkblue\">  L'IDENTIFIANT DU MENU : </span>"));
  gtk_widget_show (label20_idm);
  gtk_fixed_put (GTK_FIXED (fixed3), label20_idm, 0, 16);
  gtk_widget_set_size_request (label20_idm, 200, 40);
  gtk_label_set_use_markup (GTK_LABEL (label20_idm), TRUE);

  label32_nature = gtk_label_new (_("<span color =\"darkblue\"> ENTRER LA NATURE DE REPAS : </span>"));
  gtk_widget_show (label32_nature);
  gtk_fixed_put (GTK_FIXED (fixed3), label32_nature, 0, 272);
  gtk_widget_set_size_request (label32_nature, 232, 40);
  gtk_label_set_use_markup (GTK_LABEL (label32_nature), TRUE);

  label33_repas = gtk_label_new (_("<span color =\"darkblue\"> ENTRER LE REPAS : </span>"));
  gtk_widget_show (label33_repas);
  gtk_fixed_put (GTK_FIXED (fixed3), label33_repas, 8, 144);
  gtk_widget_set_size_request (label33_repas, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (label33_repas), TRUE);

  MODIFIER = gtk_button_new ();
  gtk_widget_show (MODIFIER);
  gtk_fixed_put (GTK_FIXED (fixed3), MODIFIER, 16, 520);
  gtk_widget_set_size_request (MODIFIER, 136, 45);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (MODIFIER), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("<span color =\"brown\"> MODIFIER </span>"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox9), label36, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  image9 = create_pixmap (fenetre_modifier, "index.png");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed3), image9, 368, 448);
  gtk_widget_set_size_request (image9, 272, 176);

  label43 = gtk_label_new ("");
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed3), label43, 168, 504);
  gtk_widget_set_size_request (label43, 200, 80);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 152, 80);
  gtk_widget_set_size_request (spinbutton1, 64, 35);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 312, 80);
  gtk_widget_set_size_request (spinbutton2, 64, 35);

  spinbutton3_adj = gtk_adjustment_new (2021, 2021, 2100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton3, 472, 80);
  gtk_widget_set_size_request (spinbutton3, 120, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 288, 136);
  gtk_widget_set_size_request (combobox1, 185, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("PETIT DEJEUNER "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("DEJEUNER"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("DINER"));

  checkbutton_22_GLUTEN = gtk_check_button_new ();
  gtk_widget_show (checkbutton_22_GLUTEN);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_22_GLUTEN, 424, 272);
  gtk_widget_set_size_request (checkbutton_22_GLUTEN, 118, 24);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (checkbutton_22_GLUTEN), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image18 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox13), image18, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("  <span color =\"chocolate\"> SANS GLUTEN </span>"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox13), label45, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  radiobutton5_HEALTHY = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton5_HEALTHY);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton5_HEALTHY, 288, 216);
  gtk_widget_set_size_request (radiobutton5_HEALTHY, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5_HEALTHY), radiobutton5_HEALTHY_group);
  radiobutton5_HEALTHY_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5_HEALTHY));

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (radiobutton5_HEALTHY), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox14), image19, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_(" <span color =\"chocolate\">HEALTHY </span>"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox14), label46, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  radiobutton6_UNHEALTHY = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton6_UNHEALTHY);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton6_UNHEALTHY, 464, 216);
  gtk_widget_set_size_request (radiobutton6_UNHEALTHY, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6_UNHEALTHY), radiobutton5_HEALTHY_group);
  radiobutton5_HEALTHY_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6_UNHEALTHY));

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (radiobutton6_UNHEALTHY), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image20 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox15), image20, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_(" <span color =\"chocolate\">UNHEALTHY</span>"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  checkbutton_11_sel = gtk_check_button_new ();
  gtk_widget_show (checkbutton_11_sel);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_11_sel, 240, 272);
  gtk_widget_set_size_request (checkbutton_11_sel, 152, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (checkbutton_11_sel), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image17 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox12), image17, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("  <span color =\"chocolate\"> SANS SEL</span>"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox12), label44, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  button_3_retour_modif = gtk_button_new ();
  gtk_widget_show (button_3_retour_modif);
  gtk_fixed_put (GTK_FIXED (fixed3), button_3_retour_modif, 536, 16);
  gtk_widget_set_size_request (button_3_retour_modif, 136, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_3_retour_modif), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image23 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox18), image23, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("<span color =\"chocolate\">  RETOURNER </span>"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox18), label50, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  g_signal_connect ((gpointer) MODIFIER, "clicked",
                    G_CALLBACK (on_MODIFIER_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_22_GLUTEN, "toggled",
                    G_CALLBACK (on_checkbutton_22_GLUTEN_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5_HEALTHY, "toggled",
                    G_CALLBACK (on_radiobutton5_HEALTHY_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6_UNHEALTHY, "toggled",
                    G_CALLBACK (on_radiobutton6_UNHEALTHY_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_11_sel, "toggled",
                    G_CALLBACK (on_checkbutton_11_sel_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_3_retour_modif, "clicked",
                    G_CALLBACK (on_button_3_retour_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_modifier, fenetre_modifier, "fenetre_modifier");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entry6_idm, "entry6_idm");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, ENTREE_2, "ENTREE_2");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entry8_PP, "entry8_PP");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, entry9_DESSERT, "entry9_DESSERT");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label21_date, "label21_date");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label22_jour, "label22_jour");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label23_mois, "label23_mois");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label24_annee, "label24_annee");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label25_type, "label25_type");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label26_REPAS, "label26_REPAS");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label27_ENTREE, "label27_ENTREE");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label28_PP, "label28_PP");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label29_DESSERT, "label29_DESSERT");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label20_idm, "label20_idm");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label32_nature, "label32_nature");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label33_repas, "label33_repas");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, MODIFIER, "MODIFIER");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image14, "image14");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label36, "label36");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label43, "label43");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, checkbutton_22_GLUTEN, "checkbutton_22_GLUTEN");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image18, "image18");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label45, "label45");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, radiobutton5_HEALTHY, "radiobutton5_HEALTHY");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image19, "image19");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label46, "label46");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, radiobutton6_UNHEALTHY, "radiobutton6_UNHEALTHY");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image20, "image20");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label47, "label47");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, checkbutton_11_sel, "checkbutton_11_sel");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image17, "image17");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label44, "label44");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, button_3_retour_modif, "button_3_retour_modif");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, image23, "image23");
  GLADE_HOOKUP_OBJECT (fenetre_modifier, label50, "label50");

  return fenetre_modifier;
}

