/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajout_menu_;
  GtkWidget *affiche_menu;
  GtkWidget *modifier;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ajout_menu_ = create_fenetre_ajout_menu_ ();
  gtk_widget_show (ajout_menu_);
  /*affiche_menu = create_fenetre_affiche_menu ();
  gtk_widget_show (affiche_menu);
  modifier = create_fenetre_modifier ();
  gtk_widget_show (modifier);*/

  gtk_main ();
  return 0;
}

